apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grpc-aggregator-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grpc-aggregator
    spec:
      containers:
        - name: grpc-aggregator
          image: gcr.io/alien-fold-180922/grpc-aggregator:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "100m"
          ports:
            - containerPort: 8080
            - containerPort: 9999
          env:
            - name: peremoga_host
              value: "grpc-peremoga-content-service"
            - name: peremoga_port
              value: "8080"
            - name: zrada_host
              value: "grpc-zrada-content-service"
            - name: zrada_port
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-aggregator-service
spec:
  type: NodePort
  selector:
    app: grpc-aggregator
  ports:
   - port: 8080
     targetPort: 8080
     protocol: TCP
---
